# Generated by Django 2.2 on 2020-03-19 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choicename', models.CharField(max_length=30, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('item', models.IntegerField()),
                ('health', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyname', models.CharField(max_length=30, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('item', models.IntegerField()),
                ('health', models.IntegerField()),
                ('choice1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hamster.Choice')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('item', models.IntegerField()),
                ('health', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
                ('choice', models.ManyToManyField(to='hamster.Choice')),
                ('story', models.ManyToManyField(to='hamster.Story')),
            ],
        ),
    ]
