# Generated by Django 2.2 on 2020-03-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hamster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='choice2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='choice2', to='hamster.Choice'),
        ),
        migrations.AddField(
            model_name='story',
            name='choice3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='choice3', to='hamster.Choice'),
        ),
        migrations.AlterField(
            model_name='story',
            name='choice1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='choice1', to='hamster.Choice'),
        ),
    ]
