# Generated by Django 2.2 on 2020-03-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamster', '0002_auto_20200324_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='choice',
            field=models.ManyToManyField(blank=True, to='hamster.Choice'),
        ),
        migrations.AlterField(
            model_name='user',
            name='story',
            field=models.ManyToManyField(blank=True, to='hamster.Story'),
        ),
    ]
