# Generated by Django 2.2 on 2020-03-30 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hamster', '0003_auto_20200324_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('hour', models.IntegerField(default=0)),
                ('item', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics')),
                ('choice', models.ManyToManyField(blank=True, to='hamster.Choice')),
                ('story', models.ManyToManyField(blank=True, to='hamster.Story')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
