# Generated by Django 2.2 on 2020-04-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamster', '0004_auto_20200330_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='health',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='item',
        ),
        migrations.RemoveField(
            model_name='story',
            name='health',
        ),
        migrations.RemoveField(
            model_name='story',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='story',
            name='item',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='health',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='item',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='story',
        ),
        migrations.AddField(
            model_name='choice',
            name='progress',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='result',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='choicename',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
